export const amenitiesArray = [
  "Heating",
  "Bath Essentials",
  "Kitchen",
  "Cooking Basics",
  "Bed Linens",
  "Hot Water Kettle",
  "Dishes And Silverware",
  "Washer",
  "Dryer",
  "Dishwasher",
  "Self Check In",
  "Cleaning Before Checkout",
  "Tv",
  "First Aid Kit",
  "Gym",
  "Iron",
  "Microwave",
  "Body Soap",
  "Hair Dryer",
  "Coffee Maker",
  "Travel Crib",
  "Hot Water",
  "Beachfront",
  "Beach View",
  "Essentials",
  "Bathroom Essentials",
  "Lockbox",
  "Air Conditioning",
  "Smoking Allowed",
  "Wifi",
  "Hangers",
  "Doorman",
  "Long Term Stays Allowed",
  "Stove",
  "Bathtub",
  "Extra Pillows And Blankets",
  "Free Parking On Premises",
  "Paid Parking On Premises",
  "Paid Parking Off Premises",
  "Bbq Grill",
  "Elevator",
  "Oven",
  "Fire Extinguisher",
  "Pool",
  "Pets Allowed",
  "Hot Tub",
  "Refrigerator",
  "Private Entrance",
  "Patio Or Balcony",
  "Minus",
  "Plus"
]